#!/bin/sh

hostname=`hostname`

usage() {
  echo "USAGE: please (deploy [BRANCH [SERVER]]|rollback [SERVER])"
  exit 1
}

notify() {
  echo $notification
  echo "{\"text\" : \"$notification FROM $hostname\"}" | curl -d @- https://projectkwl.slack.com/services/hooks/incoming-webhook?token=sSyagFIJbA8fGu38aDZXd0zn
}

if [ -z "$1" ]; then
  usage
else
  action="$1"
fi

shift

if [ "$action" = "deploy" ]; then
  if [ -z "$1" ]; then
    notification="DEPLOY default BRANCH TO staging"
    notify
    bundle exec cap staging deploy
  else
    branch="$1"
    shift
    if [[ ( -z "$1" ) || ( "$1" = "staging" ) ]]; then
      notification="DEPLOY $branch BRANCH TO staging"
      notify
      bundle exec cap staging deploy branch=$branch
    elif [ "$1" = "production" ]; then
      notification="DEPLOY $branch BRANCH TO production"
      notify
      bundle exec cap production deploy branch=$branch
    else
      usage
    fi
  fi
elif [ "$action" = "rollback" ]; then
  if [[ ( -z "$1" ) || ( "$1" = "staging" ) ]]; then
    notification="ROLLBACK staging"
    notify
    bundle exec cap staging deploy:rollback
  elif [ "$1" = "production" ]; then
    notification="ROLLBACK production"
    notify
    bundle exec cap production deploy:rollback
  else
    usage
  fi
else
  usage
fi
