#!/bin/sh

hostname=`hostname`

notify() {
  echo $notification
  echo "{\"text\" : \"$notification from $hostname\"}" | curl -d @- https://projectkwl.slack.com/services/hooks/incoming-webhook?token=sSyagFIJbA8fGu38aDZXd0zn
}

if [ "$1" = "deploy" ]; then
  shift
  if [ -z "$1" ]; then
    notification="Deploying default branch"
    notify
    bundle exec cap staging deploy
  else
    notification="Deploying $1 branch"
    notify
    bundle exec cap staging deploy branch=$1
  fi;
elif [ "$1" = "rollback" ]; then
  shift
  if [ -z "$1" ]; then
    notification="Rollback staging"
    notify
    bundle exec cap staging deploy:rollback
  else
    notification="Rollback $1"
    notify
    bundle exec cap $1 deploy:rollback
  fi;
else 
  echo "Usage: please [deploy BRANCH|rollback server]" 1>&2
  exit 1;
fi
