#!/bin/sh

# Used to connect to different hosts via ssh.
#
# All hosts can be found in .swim_hosts/
#
# Use "swim -l" to list available hosts
# Use "swim -s HOST_TOKEN" to set HOST_TOKEN as default

SRC_DIR=$(dirname $BASH_SOURCE[0])
HOSTS_DIR=$SRC_DIR/.swim_hosts

usage(){
  echo "Usage: $0 DROPLET_NAME" 1>&2
  exit 1
}

list(){
  for host in `ls -A $HOSTS_DIR | grep '^\.'`; 
    do echo ${host:1} `cat $HOSTS_DIR/$host | head -1`; 
  done
}

if [ -z $1 ];
then usage
else host_token=$1
fi 

while getopts ":ls:d" opt; do
  case $opt in
    l) list; exit 0 ;; 
    s) `cp "$HOSTS_DIR/.$OPTARG" "$HOSTS_DIR/.default"`; exit 0 ;;
    d) host_token=default ;;
    :) echo "Option -$OPTARG requires parameter" 1>&2; exit 1 ;;
  esac
done

host_file=$HOSTS_DIR/.$host_token

if [ ! -f "$host_file" ]; then 
  echo "Nonexistent host: Run 'swim -l' to see a list of available hosts" 1>&2
  exit 1 # host doesn't exist
fi

host=$(<$host_file)
ssh root@$host

