#!/bin/sh

# Used to connect to different hosts via ssh.
# All hosts can be found in .hosts/
#
# Use "swim -l" to list available hosts
# Use "swim -s HOST_TOKEN" to set HOST_TOKEN as main

SRC_DIR=$(dirname $BASH_SOURCE[0])
HOSTS_DIR=$SRC_DIR/.hosts

usage(){
  echo "Usage: $0 DROPLET_NAME" 1>&2
  exit 1
}

list(){
  for host in `ls -A $HOSTS_DIR | grep '^\.'`; 
    do echo ${host:1} `cat $HOSTS_DIR/$host | head -1`; 
  done

  exit 0
}

while getopts "ls:" opt; do
  case $opt in
    l) list ;;
    s) if [ -z $OPTARG ]; 
       then echo "No argument given for default" 1>&2; exit 1
       else `cp "$HOSTS_DIR/.$OPTARG" "$HOSTS_DIR/.default"`
       fi 
       exit 0;;
  esac
done

if [ -z $1 ]; 
then host_token=default
else host_token=$1
fi

host_file=$HOSTS_DIR/.$host_token

if [ ! -f "$host_file" ]; then 
  echo "Nonexistent host: Run 'swim -l' to see a list of available hosts" 1>&2
  exit 1 # host doesn't exist
fi

host=$(<$host_file)
ssh root@$host

