#!/bin/sh

CURRENT_TOPLEVEL=`git rev-parse --show-toplevel`
CURRENT_PROJECT=`basename $CURRENT_TOPLEVEL`
CURRENT_BRANCH=`git symbolic-ref HEAD | sed -e "s/^refs\/heads\///"`

BASE_GIT_URL='https://github.com/ProjectW'

COMPARE_URL="$BASE_GIT_URL/$CURRENT_PROJECT/compare/beta...$CURRENT_BRANCH"

open $COMPARE_URL

echo "Opened url: $COMPARE_URL"
echo "Don't forget to push your current branch to origin $CURRENT_BRANCH by running 'git push origin $CURRENT_BRANCH' "

