#!/bin/sh

usage(){
  echo "Usage: new_branch [-r] branch-name" 1>&2
  echo -e "\t-r\tCreate remote branch as well. This pushes the branch to origin," 1>&2
  echo -e "\t\t\tand sets the upstream branch for you." 1>&2
  exit 1
}

remote=false

while getopts ":r" opt; do
  case $opt in
    r)
      remote=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      ;;
  esac
done
shift $((OPTIND-1))

if [ -z "$1" ]; then
  usage
fi
branch=$1

echo "Running 'git checkout -b $1'"
git checkout -b $1
if $remote; then
  echo "Running 'git push --set-upstream origin $1'"
  git push --set-upstream origin $1
fi
